In [1]:
!pip install tensorflow numpy

In [2]:
import numpy as np

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from tensorflow.keras.utils import to_categorical

In [3]:
lyrics = [
    "love shines in the night",
    "stars glow in the sky",
    "music fills my heart",
    "dreams fly through the air",
    "love stays forever tonight",
    "moon dances with stars",
    "your smile lights my soul",
    "memories stay in my mind",
    "hearts beat with emotion",
    "songs echo in silence"
]

In [4]:
tokenizer = Tokenizer()

tokenizer.fit_on_texts(lyrics)

total_words = len(tokenizer.word_index) + 1

print(total_words)

36


In [5]:
input_sequences = []

for line in lyrics:

    token_list = tokenizer.texts_to_sequences([line])[0]

    for i in range(1, len(token_list)):

        n_gram_sequence = token_list[:i+1]

        input_sequences.append(n_gram_sequence)

print(input_sequences)

[[4, 7], [4, 7, 1], [4, 7, 1, 2], [4, 7, 1, 2, 8], [5, 9], [5, 9, 1], [5, 9, 1, 2], [5, 9, 1, 2, 10], [11, 12], [11, 12, 3], [11, 12, 3, 13], [14, 15], [14, 15, 16], [14, 15, 16, 2], [14, 15, 16, 2, 17], [4, 18], [4, 18, 19], [4, 18, 19, 20], [21, 22], [21, 22, 6], [21, 22, 6, 5], [23, 24], [23, 24, 25], [23, 24, 25, 3], [23, 24, 25, 3, 26], [27, 28], [27, 28, 1], [27, 28, 1, 3], [27, 28, 1, 3, 29], [30, 31], [30, 31, 6], [30, 31, 6, 32], [33, 34], [33, 34, 1], [33, 34, 1, 35]]


In [6]:
max_sequence_len = max(
    [len(seq) for seq in input_sequences]
)

input_sequences = np.array(
    pad_sequences(
        input_sequences,
        maxlen=max_sequence_len,
        padding='pre'
    )
)

print(input_sequences)

[[ 0  0  0  4  7]
 [ 0  0  4  7  1]
 [ 0  4  7  1  2]
 [ 4  7  1  2  8]
 [ 0  0  0  5  9]
 [ 0  0  5  9  1]
 [ 0  5  9  1  2]
 [ 5  9  1  2 10]
 [ 0  0  0 11 12]
 [ 0  0 11 12  3]
 [ 0 11 12  3 13]
 [ 0  0  0 14 15]
 [ 0  0 14 15 16]
 [ 0 14 15 16  2]
 [14 15 16  2 17]
 [ 0  0  0  4 18]
 [ 0  0  4 18 19]
 [ 0  4 18 19 20]
 [ 0  0  0 21 22]
 [ 0  0 21 22  6]
 [ 0 21 22  6  5]
 [ 0  0  0 23 24]
 [ 0  0 23 24 25]
 [ 0 23 24 25  3]
 [23 24 25  3 26]
 [ 0  0  0 27 28]
 [ 0  0 27 28  1]
 [ 0 27 28  1  3]
 [27 28  1  3 29]
 [ 0  0  0 30 31]
 [ 0  0 30 31  6]
 [ 0 30 31  6 32]
 [ 0  0  0 33 34]
 [ 0  0 33 34  1]
 [ 0 33 34  1 35]]


In [7]:
X = input_sequences[:, :-1]

y = input_sequences[:, -1]

y = to_categorical(
    y,
    num_classes=total_words
)

print(X)

print(y)

[[ 0  0  0  4]
 [ 0  0  4  7]
 [ 0  4  7  1]
 [ 4  7  1  2]
 [ 0  0  0  5]
 [ 0  0  5  9]
 [ 0  5  9  1]
 [ 5  9  1  2]
 [ 0  0  0 11]
 [ 0  0 11 12]
 [ 0 11 12  3]
 [ 0  0  0 14]
 [ 0  0 14 15]
 [ 0 14 15 16]
 [14 15 16  2]
 [ 0  0  0  4]
 [ 0  0  4 18]
 [ 0  4 18 19]
 [ 0  0  0 21]
 [ 0  0 21 22]
 [ 0 21 22  6]
 [ 0  0  0 23]
 [ 0  0 23 24]
 [ 0 23 24 25]
 [23 24 25  3]
 [ 0  0  0 27]
 [ 0  0 27 28]
 [ 0 27 28  1]
 [27 28  1  3]
 [ 0  0  0 30]
 [ 0  0 30 31]
 [ 0 30 31  6]
 [ 0  0  0 33]
 [ 0  0 33 34]
 [ 0 33 34  1]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [8]:
model = Sequential()

# Embedding Layer
model.add(
    Embedding(
        total_words,
        10,
        input_length=max_sequence_len - 1
    )
)

# First LSTM Layer
model.add(
    LSTM(
        128,
        return_sequences=True
    )
)

# Second LSTM Layer
model.add(
    LSTM(128)
)

# Output Layer
model.add(
    Dense(
        total_words,
        activation='softmax'
    )
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [9]:
model.compile(
    loss='categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

In [10]:
model.fit(
    X,
    y,
    epochs=300,
    verbose=1
)

Epoch 1/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 5s 44ms/step - accuracy: 0.0000e+00 - loss: 3.5836
Epoch 2/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.1143 - loss: 3.5801
Epoch 3/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.1143 - loss: 3.5771
Epoch 4/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.1143 - loss: 3.5743
Epoch 5/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.1143 - loss: 3.5709
Epoch 6/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.1143 - loss: 3.5664
Epoch 7/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.1143 - loss: 3.5605
Epoch 8/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.1143 - loss: 3.5542
Epoch 9/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.1143 - loss: 3.5467
Epoch 10/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.1143 - loss: 3.5356
Epoch 11/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.1143 - loss: 3.5225
Epoch 12/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.1143 

In [11]:
def generate_lyrics(seed_text, next_words):

    for _ in range(next_words):

        token_list = tokenizer.texts_to_sequences(
            [seed_text]
        )[0]

        token_list = pad_sequences(
            [token_list],
            maxlen=max_sequence_len - 1,
            padding='pre'
        )

        predicted = np.argmax(
            model.predict(token_list, verbose=0),
            axis=-1
        )[0]

        output_word = ""

        for word, index in tokenizer.word_index.items():

            if index == predicted:

                output_word = word
                break

        seed_text += " " + output_word

    return seed_text

In [12]:
print(
    generate_lyrics(
        "love",
        5
    )
)

love stays forever tonight heart stars


In [13]:
print(
    generate_lyrics(
        "music",
        5
    )
)

print(
    generate_lyrics(
        "stars",
        5
    )
)

music fills my heart soul soul
stars stays in the sky heart
